version: "3"
services:
    proxy:
        image: caddy
        container_name: clientes_proxy
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        ports:
            - 80:80
        depends_on:
            - backend
    backend:
        image: stoplight/prism:4
        container_name: clientes_mock
        command: mock --cors -h 0.0.0.0 "/AOS/clientes.yaml"
        ports:
          - 4010:4010
        volumes:
            - ./Openapi:/AOS:ro
    frontend:
        image: swaggerapi/swagger-ui
        container_name: clientes_ui
        ports:
            - 8000:8080
        environment:
            SWAGGER_JSON: /AOS/clientes.yaml
        volumes:
            - ./OpenApi:/AOS:ro
