openapi: "3.0.3"
info:
  title: "API Taller: Notificaciones"
  version: "1.0.0"
  description: 'Subsistema del env铆o de notificaciones de eventos relacionados con el taller'
  contact:
    name: Enrique Mart铆n y Eduardo Mena
    email: enrique.martin.gutierrez@alumnos.upm.es
servers:
  - url: http://127.0.0.1:80/api/v1
tags:
  - name: 'Notificaci贸n'
    description: Notificaci贸n destinada a un usuario sobre el estado de su veh铆culo en el taller.
paths:
  /notificacion:
    get:
      parameters:
      - $ref: '#/components/parameters/clienteId'
      - $ref: '#/components/parameters/orderParam'
      - $ref: '#/components/parameters/orderingParam'
      tags:
        - 'Notificaci贸n'
      summary: Obtiene todas las notificaciones de un cliente
      description: Si se introduce como parametro el id del cliente se obtienen las notificaciones de ese cliente, en el caso en el que no se especifique el par谩metro se obtendr谩n todas las notificaciones.
      operationId: notificacion_all_get
      responses:
        '200':
          description: Array de notificaciones
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                type: object
                properties:
                  notificaciones:
                    description: array de notificaciones
                    type: array
                    items:
                      $ref: '#/components/schemas/Notificacion'
              examples:
                notificacionesExamples:
                  $ref: '#/components/examples/notificaciones'
        '404':
          $ref: '#/components/responses/Response_404'
    post:
      tags:
        - 'Notificaci贸n'
      summary: Crea una nueva notificaci贸n
      description: Crea una nueva notificaci贸n para un cliente del taller introduciendo los datos siguiendo el esquema.
      operationId: notificacion_post
      requestBody:
        $ref: '#/components/requestBodies/notificacionRB'
      responses:
        '201':
          description: notificacion creada
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacion'
        '422':
          $ref: '#/components/responses/Response_422'
        '406':
          $ref: '#/components/responses/Response_406'
    options:
      tags:
        - 'Notificaci贸n'
      summary: Devuelve un resumen de las peticiones HTTP permitidas.
      description: Proporciona una cabecera de tipo `Allow` que indica los m茅todos HTTP permitidos y separados por comas.
      operationId: notificacion_all_options
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta est谩 vac铆o&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'

  '/notificacion/{notificacionId}':
    parameters:
      - $ref: '#/components/parameters/notificacionId'
    get:
      tags:
        - 'Notificaci贸n'
      summary: Obtiene una notificaci贸n concreta.
      description: Devuelve una notificaci贸n concreta identificada por su identificador (notificacionId).
      operationId: notificacion_get
      responses:
        '200':
          description: Notificacion
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacion'
        '404':
          $ref: '#/components/responses/Response_404'
    delete:
      tags:
        - 'Notificaci贸n'
      summary: Elimina una notificacion.
      description: Elimina la notificacion identificada por su identificador (notificacionId).
      operationId: notificacion_delete
      responses:
        '204':
          description: Notificacion eliminada &lt;Cuerpo de la respuesta vac铆o&gt;
        '404':
          $ref: '#/components/responses/Response_404'
    options:
      tags:
        - 'Notificaci贸n'
      summary: Devuelve un resumen de las peticiones HTTP permitidas.
      description: Proporciona una cabecera de tipo `Allow` que indica los m茅todos HTTP permitidos y separados por comas.
      operationId: notificacion_options
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta est谩 vac铆o&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'
    put:
      tags:
        - 'Notificaci贸n'
      summary: Modifica la notificaci贸n.
      description: Cambia la informaci贸n de una notificaci贸n identificada por su identificador (notificacionId)
      operationId: notificacion_put
      parameters:
        - $ref: '#/components/parameters/ifMatchParam'
      requestBody:
        $ref: '#/components/requestBodies/notificacionPutRB'
      responses:
        '200':
          description: '`OK`: la notificaci贸n ha sido actualizada con 茅xito'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacion'
        '404':
          $ref: '#/components/responses/Response_404'
        '412':
          $ref: '#/components/responses/Response_412'
        '406':
          $ref: '#/components/responses/Response_406'
components:
  schemas:
    Notificacion:
      $ref: './schemas/Notificacion.yaml#/Notificacion'
    Tipo:
      $ref: './schemas/Tipo.yaml#/Tipo'
    HTTP_Problem:
      $ref: './schemas/HTTP_Problem.yaml#/HTTP_Problem'
    Link:
      $ref: './schemas/Link.yaml#/Link'
  headers:
    ETag:
      description: Entity Tag (identificador 煤nico proporcionado para validaci贸n de cach茅)
      schema:
        type: string
        pattern: "[0-9a-f]*"
        x-faker: random.uuid
        example:
          33a64df551425fcc
    Location:
      description: '`URL` del nuevo recurso'
      schema:
        type: string
        format: url
        x-faker: internet.url
        example:
          /api/v1/notificacion/47
    Allow:
      description: Lista de m茅todos HTTP soportados
      schema:
        type: string
      example:
        GET,DELETE,PUT,OPTIONS
  parameters:
    clienteId:
      name: clienteId
      in: query
      description: ID de un cliente
      required: false
      schema:
        type: integer
        pattern: ^\d+$
    notificacionId:
      name: notificacionId
      in: path
      description: ID de una notificacion
      required: true
      schema:
        type: integer
        pattern: ^\d+$
    ifMatchParam:
      name: If-Match
      in: header
      description: ETag del recurso que se desea modificar
      required: true
      schema:
        type: string
        pattern: "[0-9a-f]*"
    orderParam:
      name: order
      in: query
      description: 'Elige atributo para ordenar: `id` o `tipo`'
      required: false
      allowEmptyValue: false
      schema:
        type: string
        enum:
          - id
          - tipo
    orderingParam:
      name: ordering
      in: query
      description: '`ASC` o `DESC`'
      required: false
      allowEmptyValue: false
      schema:
        type: string
        enum:
          - ASC
          - DESC

  requestBodies:
    notificacionRB:
      description: 'Datos de `Notificacion`'
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - tipo
              - clienteId
              - vehiculo
            properties:
              notificacionId:
                description: Id de la notificacion
                type: integer
                format: int32
              clienteId:
                 description: Id del cliente
                 type: integer
                 format: int32
              vehiculo:
                description: VIN del veh铆culo
                type: string
              tipo:
                $ref: '#/components/schemas/Tipo'
              descripcion:
                description: Descripci贸n de la notificaci贸n
                type: string
              
            example:
              notificacionId: 47
              clienteId: 23
              vehiculo: 1HGBH41JXMN109186
              tipo: Llegada
              descripcion: Tu veh铆culo acaba de ser recibido en el taller.
              links:
                notificacionesClientes:
                  href: /api/v1/notificacion?clienteId=23
                  rel: notificacionesClientes
    notificacionPutRB:
      description: 'Datos de `Notificacion`'
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              notificacionId:
                description: Id de la notificacion
                type: integer
                format: int32
              clienteId:
                 description: Id del cliente
                 type: integer
                 format: int32
              vehiculo:
                description: VIN del veh铆culo
                type: string
              tipo:
                $ref: '#/components/schemas/Tipo'
              descripcion:
                description: Descripci贸n de la notificaci贸n
                type: string
              
            example:
              notificacionId: 47
              clienteId: 23
              vehiculo: 1HGBH41JXMN109186
              tipo: Llegada
              descripcion: Tu veh铆culo acaba de ser recibido en el taller.
              links:
                notificacionesClientes:
                  href: /api/v1/notificacion?clienteId=23
                  rel: notificacionesClientes
  responses:
    Response_404:
      description: '`NOT FOUND`: recurso no disponible'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-404:
              $ref: '#/components/examples/response-http-404'
    Response_412:
      description: '`PRECONDITION FAILED`: no se cumple alguna condici贸n previa'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-412:
              $ref: '#/components/examples/response-http-412'
    Response_422:
      description: '`UNPROCESSABLE ENTITY`: Falta alguno de los atributos requeridos o son err贸neos(clienteId, vehiculo o tipo)...'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-422:
              $ref: '#/components/examples/response-http-422'
    Response_406:
      description: '`NOT ACCEPTABLE`: El id del cliente o del veh铆culo que se ha proporcionado no corresponde con ninguno existente'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-406:
              $ref: '#/components/examples/response-http-406'

  examples:
    notificaciones:
      value:
        - notificacionId: 47
          clienteId: 23
          vehiculo: 1HGBH41JXMN109186
          tipo: Llegada
          descripcion: Tu veh铆culo acaba de ser recibido en el taller.
          links:
              notificacionesClientes:
                href: /api/v1/notificacion?clienteId=23
                rel: notificacionesClientes
        - notificacionId: 48
          clienteId: 24
          vehiculo: 1HGBH41JXMN109187
          tipo: Salida
          descripcion: Tu veh铆culo acaba de salir del taller.
          links:
              notificacionesClientes:
                href: /api/v1/notificacion?clienteId=24
                rel: notificacionesClientes
    notificacionesCliente:
      value:
        - notificacionId: 47
          clienteId: 23
          vehiculo: 1HGBH41JXMN109186
          tipo: Llegada
          descripcion: Tu veh铆culo acaba de ser recibido en el taller.
          links:
              notificacionesClientes:
                href: /api/v1/notificacion?clienteId=23
                rel: notificacionesClientes
        - notificacionId: 49
          clienteId: 23
          vehiculo: 1HGBH41JXMN109187
          tipo: Salida
          descripcion: Tu veh铆culo acaba de salir del taller.
          links:
              notificacionesClientes:
                href: /api/v1/notificacion?clienteId=23
                rel: notificacionesClientes
    response-http-404:
      value:
        type: https://httpstatuses.com/404
        title: NOT FOUND
        status: 404
        detail: El recurso solicitado no est谩 disponible...
        instance: about:blank
    response-http-412:
      value:
        type: https://httpstatuses.com/412
        title: PRECONDITION FAILED
        status: 412
        detail: No se cumple alguna condici贸n previa...
        instance: about:blank
    response-http-422:
      value:
        type: https://httpstatuses.com/422
        title: UNPROCESSABLE ENTITY
        status: 422
        detail: Falta alguno de los atributos requeridos o son err贸neos(clienteId, vehiculo o tipo)...
        instance: about:blank
    response-http-406:
      value:
        type: https://httpstatuses.com/406
        title: NOT ACCEPTABLE
        status: 406
        detail: El id del cliente o del veh铆culo que se ha proporcionado no corresponde con ninguno existente
        instance: about:blank
