version: "3"

services:
  clientes:
      image: jmenesesf/aos-develop:latest
      ports:
        - "5000:5000"
      networks:
        - taller-api

  facturas:
      image: eloz/grupo8facturas:latest
      ports:
        - "81:80"
      networks:
        - taller-api


  vehiculos-backend:
      image: stoplight/prism:4
      container_name: vehicles_mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4016:4010"
      volumes:
          - ./openapi_vehiculos:/aos:ro

  vehiculos-frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: vehicles_ui
      ports:
          - "8006:8080"
      environment:
          SWAGGER_JSON: /aos/openapi.yaml
      volumes:
          - ./openapi_vehiculos:/aos:ro

  notificaciones:
        image: enriquer47/api_notificaciones:0.0.1
        container_name: notificaciones_service
        ports:
        - 7777:5000
        networks:
        - taller-api  
  
  logs-backend:
        image: stoplight/prism:4
        container_name: log_mocks
        command: mock --cors -h 0.0.0.0 "/logs/openapi.yaml"
        ports:
          - 8081:4010
        volumes:
            - ./openapi_logs:/logs:ro
  logs-frontend:
        image: swaggerapi/swagger-ui:latest
        container_name: logs_ui
        ports:
            - 8001:8080
        environment:
            SWAGGER_JSON: /logs/openapi.yaml
        volumes:
            - ./openapi_logs:/logs:ro

  recambios:
    image: ghcr.io/adrianja5/aos-implementacion-servicio-recambios
    ports: 
      - "8095:4010"
    networks:
      - taller-api

  trabajos-backend:
        image: stoplight/prism:4
        container_name: trabajos-backend
        command: mock --cors -h 0.0.0.0 "/aos/swagger.yaml"
        ports:
          - 8091:4010
        volumes:
            - ./openapi_trabajos:/aos:ro
  trabajos-frontend:
    image: swaggerapi/swagger-ui
    container_name: trabajos-frontend
    environment:
        SWAGGER_JSON: /api/swagger.yaml
    volumes:
        - ./openapi_trabajos:/api:ro
    ports:
      - 8090:8080
networks:
  taller-api:
volumes:
  db_data: